### ISSUE TITLE
about documentations?

### ISSUE THREAD

**Issue by nevernet** [Dwarfartisan/goparsec2#3]
is there any docs? 
regarding to how to use this library

thanks

**Comment by MarchLiu** [comment]
Go Parsec 2 has some document used Chinese as [https://zhuanlan.zhihu.com/p/20262167](https://zhuanlan.zhihu.com/p/20262167) . But it hasn't English Document. 

It is a project begon for a business project. I written it for some tiny parsers. But now, my team use java and clojure more than golang. I am almost only one developer for goparsec2. I need some party time for improve it.

Sorry for the delay. I will try to find some time to do it. Thank you for your post.
