### ISSUE TITLE
如何处理带有不同优先级算符的表达式？

### ISSUE THREAD

**Issue by Icarus0xff** [Dwarfartisan/goparsec2#5]
Haskell中可以通过用buildExpressionParser函数传入符号优先级表生成支持算符优先级的parser，goparsec2中应当怎样处理呢？

**Comment by MarchLiu** [comment]
暂时没好办法，只能手工实现(//////)

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Icarus0xff** [comment]
目前是采用先写bnf，比如
```
e := e + e | e - e | t 
t := t * t | t / t | num
num := (0-9)*
```
然后消除左递归，按照转化出来的bnf写代码的。

**Comment by g101418** [comment]
1+2*3/2-1
