### ISSUE TITLE
license text is incorrect

### ISSUE THREAD

**Issue by jba** [Dwarfartisan/goparsec2#6]
In three places in the LICENSE file, you have the word `Expect` where it should be `except`.

```
Expect as stated
Expect as required
Expect in compliance
```

pkg.go.dev may no longer be able to display docs for your package if this isn't fixed.

**Comment by MarchLiu** [comment]
done. thx.

**Comment by jba** [comment]
It's not just the uppercase `E`, it's a different word.

have: e x p e c t
want: e x c e p t

**Comment by MarchLiu** [comment]
Em... It's my failure about English. But the word 'expect' is used to describe a 'result been expect', not a 'excepted result'. For example in source: 

```
t.Fatalf("Expect 8080 but %v", output[1])
```

What is try to get the port number 8080, but the value is not.
